name: producthunt
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.2.0
  camera: ^0.11.0+1
  device_info_plus: ^10.1.0
  file_picker: ^8.0.6
  flex_color_picker: ^3.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_staggered_grid_view: ^0.7.0
  fpdart: ^1.1.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  hive: ^4.0.0-dev.2
  icon_decoration: ^2.0.2
  image_picker: ^1.1.2
  isar_flutter_libs: ^4.0.0-dev.13
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^8.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21
